### ISSUE TITLE
k8s - How to remove password from application.properties?

### ISSUE THREAD

**Issue by thatguyfig** [featurehub-io/featurehub-install#21]
I would like to remove the password from the application.properties file created by the app-config secret. 

I've tried to instead reference an environment variable in the file in the hope the application would interpolate its value. For example:

`db.password=$DB_PASSWORD`

Then in my container spec I mount a secret for the database password, however the container fails to start. Attaching to the pod I can see the environment var is there, but I don't think it's understood by the underlying java application and fails to login to the database.

Why am I trying to do this? So that I can isolate the secrets out of the application config, and use an external secrets controller to automatically update the secrets should they be changed externally.

hopefully I'm missing something I didn't see in the docs

**Comment by rvowles** [comment]
Heya, are you using docker or kubernetes? and which server config are you using? If you are using docker, how are you running it?

**Comment by thatguyfig** [comment]
I'm using AWS EKS based Kubernetes and the setup is basically everything but the ingress and postgres as we are using RDS instead

**Comment by rvowles** [comment]
Ah, right - you changed it to k8s - if you want to load secrets file, we provide an extra file now specifically to allow you to load secrets via the k8s secrets mechanism and keep them separate from a k8s configmap. 

                  <arg>-P/etc/common-config/common.properties</arg>
                  <arg>-P/etc/app-config/application.properties</arg>
                  <arg>-P/etc/app-config/secrets.properties</arg>

This should allow you to easily separate them. But environment variables do not override the properties files, the reverse is true.

**Comment by rvowles** [comment]
We tried to make that a bit more k8s friendly because of exactly your question :-)

**Comment by rvowles** [comment]
Perhaps if you could raise a ticket on the featurehub-examples so we update the k8s example and this will make it easier for people going forward? Its an excellent point!

**Comment by thatguyfig** [comment]
Yes Im aware of those secrets that get created, my problem is that the plain text password is essentially written to those files on the pod. What I'd like to do instead is reference an environment variable in the file instead which points to the environment variable instead. 

The reason for this is because these passwords will be rotated on a regular basis, and we need a way to always ensure the password is correct. We can't store the plain password in the chart, as it lives in git.

**Comment by thatguyfig** [comment]
Sorry I just realised you posted a third properties file called `secrets.properties`, I've been developing on probably an older chart which doesn't have that so ill look at updating my local copy. 

Do you have any guidance on how to use the file? Does it get merged with the application.properties file?

**Comment by rvowles** [comment]
They merge in order, so it reads in the common.properties, then the application.properties and then the secrets.properties file - its not on the current chart as it was included in 1.5.0 and we didn't update the chart to match the new file. The idea was that you could use common.properties across common things (across all pods), application.properties that were not-secret and specific to a pod, and secrets for secrets.

**Comment by rvowles** [comment]
that means the values in secrets.properties have the highest precedence, application.properties the middle and common.properties the lowest

**Comment by thatguyfig** [comment]
So you're saying if mount a file to `/etc/app-config/secrets.properties` in the current chart this will work?

I assume it will work in the same way as application.properties except you can now remove the password there. Is that correct?

**Comment by rvowles** [comment]
That is correct 👍

**Comment by rvowles** [comment]
Feel free to jump on our Slack if you need more real-time answers, we are on nzdt timezone.

**Comment by thatguyfig** [comment]
Ok great, this will work for my use case as the other variables aren't that important. The problem really lies in the way k8s does secrets, it doesn't support templating so you can't reference a secret inside another secret or config map, there's still an ongoing thread about it.

Thanks let you know if I have any issues with it working tomorrow - have to update my chart first 🙂

**Comment by rvowles** [comment]
I'm wondering if this is more complex than it should be? I've just been looking at the chart - if you remove db.password from the api-config.yaml, then you can mount it as an environment variable instead. Its just that because it is in the api-config.yaml, it won't look at the environment variable.

**Comment by thatguyfig** [comment]
That's even better, I'll try it out Monday. 🙂

I read somewhere in the changelog for 1.5.0 that environment variables are now interpreted correctly, and before you had to modify them slightly. 

`deployment configuration - all configuration properties are now available in the same case as environment variables, previously they were required to be upper case and have . replaced with _. We did this for environments like Cloud Run and ECS.`

I'm guessing then in my version I'll have to mount the environment variable as DB_PASSWORD? As in 1.5.0 you can just use db.password.

**Comment by thatguyfig** [comment]
Hi all,

I was able to do this fairly easily, just using environment variables in the end. Here is they way i've done it:

First of all ensure you are using the latest container image (version 1.5.0):

1. Create an external secret as described here - https://github.com/external-secrets/kubernetes-external-secrets
2. Mount the secret you created earlier to the pod as an environment var (in mr-deployment.yaml), such as:

```yaml
      containers:
        - name: {{ include "featurehub.managementRepository.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.managementRepository.image.repository }}:{{ .Values.managementRepository.image.tag | default .Chart.AppVersion }}"
          env:
            - name: db.username
              valueFrom:
                secretKeyRef:
                  name: postgres-details
                  key: username
            - name: db.password
              valueFrom:
                secretKeyRef:
                  name: postgres-details
                  key: password
            - name: db.url
              valueFrom:
                secretKeyRef:
                  name: postgres-details
                  key: url
```

3. Ensure to remove any hardcoding of these values from application.properties - created by api-config.yaml or values.yaml.

You container should launch using the environment vars instead.

@rvowles  - let me know if you want me to share the 1.5.0 Chart i've created for easy use on featurehub-examples, as there is in fact 0 documentation for k8s on there I believe.
