### ISSUE TITLE
fix wrong image tag format in values.yaml

### ISSUE THREAD

**Issue by pyromaniac3010** [featurehub-io/featurehub-install#40]
the default values file has non working image tags:

```
managementRepository:
  image:
    repository: featurehub/mr
    tag: :1.5.6
edge:
  image:
    repository: featurehub/edge
    tag: :1.5.6
dacha:
  image:
    repository: featurehub/dacha
    tag: :1.5.6
```
The redundant : leads to the following error:
```
Failed to apply default image tag "featurehub/dacha::1.5.6": couldn't parse image reference "featurehub/dacha::1.5.6": invalid reference format
```
